runtime: nodejs22
service: website
entrypoint: npm run start

env_variables:
  NODE_ENV: production
  PORT: "8080"
  FIREBASE_SERVICE_ACCOUNT: 'PASTE_YOUR_FIREBASE_SERVICE_ACCOUNT_JSON_HERE'
  SESSION_SECRET: 'PASTE_YOUR_SESSION_SECRET_HERE'

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.65

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
